# Generated by Django 5.0.4 on 2024-05-17 17:15

import django.db.models.deletion
import documento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlinkpdf',
            name='empresa',
            field=models.ForeignKey(default=documento.models.default_empresa_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.empresa'),
        ),
    ]
