# Generated by Django 5.0.4 on 2024-05-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_alter_hyperlinkpdf_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperlinkDadosNull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateField()),
                ('caminho', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('dta_documento', models.DateField(null=True)),
                ('codigo_documento', models.CharField(max_length=255)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.cargo')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.colaborador')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.tipodocumento')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.empresa')),
                ('regional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.regional')),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.unidade')),
            ],
            options={
                'db_table': 'hyperlink_dados_null',
            },
        ),
    ]
